version: '3.3'
services:
  db:
    image: postgres
    container_name: 2ofClubsDB
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - db.env
    networks:
      - backend
    volumes:
      - 2ofClubsVolume:/var/lib/postgresql/data
  app:
    container_name: 2ofClubsServer
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - app.env
    ports:
      - "8080:8080"
    command: go run main.go
volumes:
  2ofClubsVolume:
networks:
  backend:
    driver: "bridge"


